"""Species reference data: wood density, growth constants, commercial names.

Wood densities (rho, g/cm3) — Central African timber species.
Growth constants for Chapman-Richards D(t) = A * (1 - e^(-k t))^p fitted
from published increment data (FORAFRI/Engone Obiang for Okoume; literature
ranges for the other species — refined via RAG ingestion pipeline).

A large reference cohort (African species with wood density from the Global
Wood Density Database) is loaded at import time from ``data/species_reference.json``
(generated by ``tools.expand_corpus``). Curated profiles below always take
precedence over the generated cohort.
"""

import json
from dataclasses import dataclass, field, replace
from pathlib import Path


@dataclass(frozen=True)
class SpeciesProfile:
    scientific_name: str
    common_name_fr: str
    wood_density_g_cm3: float
    # Chapman-Richards asymptotic DBH (cm), rate, shape
    cr_asymptote_a_cm: float
    cr_rate_k: float
    cr_shape_p: float
    # Height-diameter hyperbolic parameters: H = 1.3 + a * D / (b + D)
    hd_a: float = 40.0
    hd_b: float = 25.0
    iucn_status: str = "LC"
    max_height_m: float = 40.0
    aliases: tuple = field(default_factory=tuple)
    family: str = ""
    cr_source: str = "literature"
    cites_appendix: str = ""
    eu_listing: str = ""
    # True for the curated Central African cohort; generated species carry the
    # value inferred from GBIF/WCVP range data (None when unknown).
    native_to_africa: bool | None = True


_CURATED_SPECIES: dict[str, SpeciesProfile] = {
    "Aucoumea klaineana": SpeciesProfile(
        scientific_name="Aucoumea klaineana",
        common_name_fr="Okoumé",
        wood_density_g_cm3=0.44,
        cr_asymptote_a_cm=80.0,
        cr_rate_k=0.035,
        cr_shape_p=1.20,
        hd_a=40.0,
        hd_b=25.0,
        iucn_status="VU",
        max_height_m=40.0,
        aliases=("okoume", "okoumé", "gaboon mahogany"),
    ),
    "Lophira alata": SpeciesProfile(
        scientific_name="Lophira alata",
        common_name_fr="Azobé",
        wood_density_g_cm3=1.06,
        cr_asymptote_a_cm=140.0,
        cr_rate_k=0.012,
        cr_shape_p=1.50,
        iucn_status="VU",
        max_height_m=50.0,
        aliases=("azobe", "azobé", "belli"),
    ),
    "Pterocarpus soyauxii": SpeciesProfile(
        scientific_name="Pterocarpus soyauxii",
        common_name_fr="Padouk",
        wood_density_g_cm3=0.75,
        cr_asymptote_a_cm=100.0,
        cr_rate_k=0.020,
        cr_shape_p=1.30,
        iucn_status="LC",
        max_height_m=40.0,
        aliases=("padouk", "padauk", "african padauk"),
    ),
    "Dacryodes glaucescens": SpeciesProfile(
        scientific_name="Dacryodes glaucescens",
        common_name_fr="Ozigo",
        wood_density_g_cm3=0.47,
        cr_asymptote_a_cm=90.0,
        cr_rate_k=0.025,
        cr_shape_p=1.25,
        iucn_status="LC",
        max_height_m=35.0,
        aliases=("ozigo", "cinnamomum glaucescens"),
    ),
    "Baillonella toxisperma": SpeciesProfile(
        scientific_name="Baillonella toxisperma",
        common_name_fr="Moabi",
        wood_density_g_cm3=0.83,
        cr_asymptote_a_cm=120.0,
        cr_rate_k=0.015,
        cr_shape_p=1.40,
        iucn_status="EN",
        max_height_m=45.0,
        aliases=("moabi", "djita", "adjap"),
    ),
    # --- Second cohort: major Gabonese timber + NTFP (community income) ---
    # CR parameters are provisional (literature ranges / expert prior) pending
    # local increment-data fitting; densities follow CIRAD/ITTO Tropical Timber
    # atlases for Central African species.
    "Entandrophragma cylindricum": SpeciesProfile(
        scientific_name="Entandrophragma cylindricum",
        common_name_fr="Sapelli",
        wood_density_g_cm3=0.60,
        cr_asymptote_a_cm=95.0,
        cr_rate_k=0.020,
        cr_shape_p=1.30,
        hd_a=42.0,
        hd_b=25.0,
        iucn_status="VU",
        max_height_m=45.0,
        aliases=("sapelli", "sapele", "aboudikro"),
    ),
    "Entandrophragma utile": SpeciesProfile(
        scientific_name="Entandrophragma utile",
        common_name_fr="Sipo",
        wood_density_g_cm3=0.62,
        cr_asymptote_a_cm=90.0,
        cr_rate_k=0.022,
        cr_shape_p=1.30,
        hd_a=42.0,
        hd_b=25.0,
        iucn_status="LC",
        max_height_m=45.0,
        aliases=("sipo", "assie", "assié"),
    ),
    "Milicia excelsa": SpeciesProfile(
        scientific_name="Milicia excelsa",
        common_name_fr="Iroko",
        wood_density_g_cm3=0.64,
        cr_asymptote_a_cm=100.0,
        cr_rate_k=0.021,
        cr_shape_p=1.35,
        hd_a=42.0,
        hd_b=25.0,
        iucn_status="LC",
        max_height_m=40.0,
        aliases=("iroko", "kambala", "mvule", "abang"),
    ),
    "Terminalia superba": SpeciesProfile(
        scientific_name="Terminalia superba",
        common_name_fr="Fraké",
        wood_density_g_cm3=0.52,
        cr_asymptote_a_cm=110.0,
        cr_rate_k=0.030,
        cr_shape_p=1.40,
        hd_a=40.0,
        hd_b=24.0,
        iucn_status="LC",
        max_height_m=45.0,
        aliases=("frake", "fraké", "limba", "limba blanc"),
    ),
    "Cylicodiscus gabunensis": SpeciesProfile(
        scientific_name="Cylicodiscus gabunensis",
        common_name_fr="Okan",
        wood_density_g_cm3=0.88,
        cr_asymptote_a_cm=95.0,
        cr_rate_k=0.017,
        cr_shape_p=1.50,
        hd_a=41.0,
        hd_b=26.0,
        iucn_status="LC",
        max_height_m=50.0,
        aliases=("okan", "adenkama"),
    ),
    "Irvingia gabonensis": SpeciesProfile(
        scientific_name="Irvingia gabonensis",
        common_name_fr="Andok (mangue sauvage)",
        wood_density_g_cm3=0.72,
        cr_asymptote_a_cm=80.0,
        cr_rate_k=0.028,
        cr_shape_p=1.30,
        hd_a=38.0,
        hd_b=22.0,
        iucn_status="LC",
        max_height_m=35.0,
        aliases=("andok", "andog", "mangue sauvage", "wild mango"),
    ),
    "Ricinodendron heudelotii": SpeciesProfile(
        scientific_name="Ricinodendron heudelotii",
        common_name_fr="Njansang",
        wood_density_g_cm3=0.36,
        cr_asymptote_a_cm=85.0,
        cr_rate_k=0.038,
        cr_shape_p=1.35,
        hd_a=38.0,
        hd_b=22.0,
        iucn_status="LC",
        max_height_m=35.0,
        aliases=("njansang", "essessang", "erimado"),
    ),
}


def _load_generated_reference() -> dict[str, SpeciesProfile]:
    """Load the generated African species cohort (if present)."""
    path = Path(__file__).resolve().parents[2] / "data" / "species_reference.json"
    try:
        entries = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    loaded: dict[str, SpeciesProfile] = {}
    for entry in entries:
        name = entry.get("scientific_name")
        if not name:
            continue
        loaded[name] = SpeciesProfile(
            scientific_name=name,
            common_name_fr=entry.get("common_name_fr") or "",
            wood_density_g_cm3=float(entry["wood_density_g_cm3"]),
            cr_asymptote_a_cm=float(entry.get("cr_asymptote_a_cm", 100.0)),
            cr_rate_k=float(entry.get("cr_rate_k", 0.022)),
            cr_shape_p=float(entry.get("cr_shape_p", 1.35)),
            family=entry.get("family") or "",
            cr_source=entry.get("cr_source") or "reference",
            iucn_status=entry.get("iucn_status") or "NE",
            cites_appendix=entry.get("cites_appendix") or "",
            eu_listing=entry.get("eu_listing") or "",
            aliases=tuple(entry.get("aliases") or []),
            native_to_africa=entry.get("native_to_africa"),
        )
    return loaded


# Generated cohort first so curated profiles win on any name collision.
SPECIES_DB: dict[str, SpeciesProfile] = {
    **_load_generated_reference(),
    **_CURATED_SPECIES,
}


# Curated trade / local names for high-value Central African species, incl. the
# CITES-listed timbers whose generated cohort has no aliases of its own.
_TRADE_ALIASES: dict[str, tuple[str, ...]] = {
    "Guibourtia demeusei": ("kevazingo", "bubinga", "akume", "essak"),
    "Guibourtia tessmannii": ("kevazingo", "bubinga", "gabon rosewood"),
    "Guibourtia pellegriniana": ("kevazingo", "bubinga"),
    "Pericopsis elata": ("assamela", "afrormosia", "kokrodua", "obang"),
    "Khaya anthotheca": ("african mahogany", "white mahogany", "acajou"),
    "Khaya ivorensis": ("african mahogany", "acajou bassam", "lagos mahogany"),
    "Khaya grandifoliola": ("african mahogany", "benin mahogany"),
    "Khaya senegalensis": ("african mahogany", "dry zone mahogany"),
    "Pterocarpus erinaceus": ("kino", "barwood", "african rosewood"),
    "Pterocarpus angolensis": ("mukwa", "kiaat", "african teak"),
    "Afzelia africana": ("doussie", "lingue"),
    "Afzelia bipindensis": ("doussie", "lingue"),
    "Prunus africana": ("pygeum", "african cherry", "red stinkwood"),
    "Entandrophragma cylindricum": ("sapelli", "sapele", "aboudikro"),
    "Entandrophragma utile": ("sipo", "assie"),
}


def _load_listings() -> dict[str, dict]:
    path = Path(__file__).resolve().parents[2] / "data" / "listings_cache.json"
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}


def _apply_overlays(
    profiles: dict[str, SpeciesProfile],
) -> dict[str, SpeciesProfile]:
    """Merge trade aliases and latest CITES/EU listings into the registry.

    Keeps curated profiles authoritative for growth/density while reflecting
    ``data/listings_cache.json`` (produced by ``tools.import_listings``).
    """
    cache = _load_listings()
    out: dict[str, SpeciesProfile] = {}
    for name, profile in profiles.items():
        aliases = tuple(dict.fromkeys((*profile.aliases, *_TRADE_ALIASES.get(name, ()))))
        entry = cache.get(name)
        changes: dict = {}
        if aliases != profile.aliases:
            changes["aliases"] = aliases
        if entry:
            if entry.get("cites_appendix"):
                changes["cites_appendix"] = entry["cites_appendix"]
            if entry.get("eu_listing"):
                changes["eu_listing"] = entry["eu_listing"]
        out[name] = replace(profile, **changes) if changes else profile
    return out


SPECIES_DB = _apply_overlays(SPECIES_DB)

DEFAULT_SPECIES = _CURATED_SPECIES["Aucoumea klaineana"]
DEFAULT_WOOD_DENSITY = 0.62  # mean Central African moist forest


def resolve_species(name: str | None) -> SpeciesProfile | None:
    """Resolve a free-text name to a profile.

    Exact matches on the scientific name or any alias win; curated profiles are
    checked first so authoritative local names beat generated vernaculars.
    A substring fallback (min length 4) handles partial input.
    """
    if not name:
        return None
    key = name.strip().lower()
    if len(key) < 3:
        return None

    ordered = [SPECIES_DB[n] for n in _CURATED_SPECIES if n in SPECIES_DB]
    ordered += [p for n, p in SPECIES_DB.items() if n not in _CURATED_SPECIES]

    for profile in ordered:
        if key == profile.scientific_name.lower() or key in profile.aliases:
            return profile

    best: SpeciesProfile | None = None
    best_len = 1 << 30
    for profile in ordered:
        for alias in profile.aliases:
            if len(key) >= 4 and len(alias) >= 4 and (key in alias or alias in key):
                span = max(len(alias), len(key))
                if span < best_len:
                    best_len, best = span, profile
    return best


def wood_density_for(name: str | None) -> float:
    profile = resolve_species(name)
    return profile.wood_density_g_cm3 if profile else DEFAULT_WOOD_DENSITY
